version: '3.8'
services:
  db:
    container_name: task_management_api_db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5433
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_management
    volumes:
      - .:/data:/var/lib/postgresql/data
